### ISSUE TITLE
Challenge: The maximum number of submissions this day have been reached.

### ISSUE THREAD

**Issue by Tobias-Fischer** [mapillary/mapillary_sls#11]
Hiya,
Unfortunately I receive the error "The maximum number of submissions this day have been reached." although I have not made a submission today yet. My last (and only) submission was at 08/18/2020 20:31:21; now the server time is 08/19/2020, 9:43:00, which is both a new day and more than 24 hours since the last submission.

It would be great if you could look into this.

Many thanks, Tobias

**Comment by mlopezantequera** [comment]
Can you submit already? I wonder if it has to do with timezones (e.g. days being separated only on UTC or something like that). Looking into this

**Comment by Tobias-Fischer** [comment]
I still cannot submit. Server time now Aug. 20, 2020, 9:05 a.m.

**Comment by mlopezantequera** [comment]
We're fixing it - there is an error in the backend forcing the wait to be 48h. You should be able to submit in a few hours or once we push the fix (whichever comes first).

Thanks for letting us know and sorry for the inconvenience

**Comment by Tobias-Fischer** [comment]
Thanks @mlopezantequera
