### ISSUE TITLE
Information about framerate

### ISSUE THREAD

**Issue by ffabi** [mapillary/mapillary_sls#14]
Hi, thanks for the contribution!

Is it possible to calculate the time difference between two frames? 
The raw.csv file contains a column `captured_at`, but it is only a date, not capture time with millisecond accuracy.
Other than that, I could not find any information about framerate / fps / time difference in your repository, in the sample dataset or on the mapillary sls site. 

Thanks, Fabian

**Comment by mlopezantequera** [comment]
We didn't save the full timestamp, but it is available through the Mapillary API. You can query using the image keys and will get access to more metadata: 

https://www.mapillary.com/developer/api-documentation/#the-image-object

**Comment by ffabi** [comment]
Thanks for the quick reply!
I will look into the API then.
