### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by gmberton** [mapillary/mapillary_sls#16]
Hello, are you planning to release the entire code used to train the networks on MSLS? Specifically, I'm referring to Tab.3 in the main paper and Tab.1 in the supplementary (which uses the "Positive Mining Strategy")

**Comment by Lu-Feng** [comment]
> the entire code used to train the networks

Hi, have you got the entire code used to train the network? I need it too.

**Comment by gmberton** [comment]
> > the entire code used to train the networks
> 
> Hi, have you got the entire code used to train the network? I need it too.

Hello, we made a framework to train it here https://github.com/gmberton/benchmarking_vg
