### ISSUE TITLE
Downloading the dataset from CLI

### ISSUE THREAD

**Issue by vturrisi** [mapillary/mapillary_sls#17]
Hey,
Is there any easy way to download the dataset via cli in a remote server?
Thanks.

**Comment by vturrisi** [comment]
Manage to download with `curl`. `wget` was giving me a permission error.

**Comment by YvanYin** [comment]
@vturrisi Have you solved the issue of downloading with curl or wget? I also want to download mapillary datset to our uni server.

**Comment by vturrisi** [comment]
@YvanYin I solved with curl. You can do something like: `curl URL --output OUTPUT.zip`
