### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by Jeff-Zilence** [mapillary/mapillary_sls#21]
Thank you for this nice work. 
I am trying to download the dataset following the standard instruction. All the links are working well except the second zip file: "msls_images_vol_2.zip ". Could you please check and verify this link?

**Comment by mlopezantequera** [comment]
Links work fine on my side. Can you try from a different computer, perhaps from an incognito browser tab?

**Comment by Jeff-Zilence** [comment]
> Links work fine on my side. Can you try from a different computer, perhaps from an incognito browser tab?

Thank you for your quick reply. I have checked on the other computer, but the "msls_images_vol_2.zip " still does not work. Is there any other way to download the second one? The other ones are working well.

**Comment by mlopezantequera** [comment]
When you say it doesn't work, what do you mean?
________________________________

**Comment by Jeff-Zilence** [comment]
> When you say it doesn't work, what do you mean?
> […](#)

When I click the link for the second file, I get "HTTP ERROR 400".

**Comment by Jeff-Zilence** [comment]
I have tried using different accounts, different browsers, incognito browser tab and different computers. The link of the second file either has no response on Firefox or returns "HTTP ERROR 400" on Chrome.
Is it possible to check the link of "msls_images_vol_2.zip" specifically? Is there any alternative way to download this file?
![image](https://user-images.githubusercontent.com/46680018/146040002-393ddd91-9a52-4a33-9a95-165f402779c4.png)
