### ISSUE TITLE
msls_images_vol_1.zip download fail

### ISSUE THREAD

**Issue by Subury** [mapillary/mapillary_sls#22]
All files can be downloaded normally, but only the "msls_images_vol_1.zip" file failed to download, and the web page reported an error 400. I saw this problem in other documents before. Does this one need to wait for a period of time?

**Comment by mlopezantequera** [comment]
I think this might be some issue related to the content distribution network and your specific location / ip. Someone else had [similar issues](https://github.com/mapillary/mapillary_sls/issues/21) (with another file). Perhaps wait a bit or try to download from another IP?

**Comment by Subury** [comment]
@mlopezantequera Tanks. I will try. I looked at the previous issue record and found some questions about the competition. Has this data set ever held a competition? If so, can you give me a link?

**Comment by Subury** [comment]
Excuse me, I have tried to change different download methods and IP addresses, but unfortunately, I still cannot download these files. So are there any other downloads of this dataset?

**Comment by mlopezantequera** [comment]
Currently the evaluation server is not enabled, we're working on hopefully setting up a permanent ongoing eval server.

@Subury  did you manage to download or are there still files that you can't access?

**Comment by mlopezantequera** [comment]
@Subury  the eval server is back online, read more here:

https://github.com/mapillary/mapillary_sls/#-evaluate-on-the-test-set
