### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by xuzhuang1996** [mapillary/mapillary_sls#27]
hi, I want to upload my zip to CodaLab,but I got this result "Sorry, failed to upload file."
![image](https://user-images.githubusercontent.com/24559901/160586107-2fd8eb91-c21b-4a38-96dc-8e6ede5c8bb9.png)
can you tell me how to fix it?
thank you very much

**Comment by mlopezantequera** [comment]
Hi! Please:

1. Make sure that your submission format is correct (only one .csv file in the **root** of the zip file)
2. If the problem persists, it might be related to codalab. Please check their [Google Group](https://groups.google.com/forum/#!forum/codalab-competitions) or their [GitHub Issues](https://github.com/codalab/codalab-competitions/issues)

**Comment by xuzhuang1996** [comment]
> Hi! Please:
> 
> 1. Make sure that your submission format is correct (only one .csv file in the **root** of the zip file)
> 2. If the problem persists, it might be related to codalab. Please check their [Google Group](https://groups.google.com/forum/#!forum/codalab-competitions) or their [GitHub Issues](https://github.com/codalab/codalab-competitions/issues)

this is my zip:
![image](https://user-images.githubusercontent.com/24559901/160594680-e5af155c-4bb9-48c5-a560-40feb10d4b9e.png)
I will check the codalab-competitions's issues.
thank you very much!

**Comment by xuzhuang1996** [comment]
> > Hi! Please:
> > 
> > 1. Make sure that your submission format is correct (only one .csv file in the **root** of the zip file)
> > 2. If the problem persists, it might be related to codalab. Please check their [Google Group](https://groups.google.com/forum/#!forum/codalab-competitions) or their [GitHub Issues](https://github.com/codalab/codalab-competitions/issues)
> 
> this is my zip: ![image](https://user-images.githubusercontent.com/24559901/160594680-e5af155c-4bb9-48c5-a560-40feb10d4b9e.png) I will check the codalab-competitions's issues. thank you very much!

This seems to be the codalab-competitions problem! 

I will close this issue!
