### ISSUE TITLE
can't download the Mapillary dataset 

### ISSUE THREAD

**Issue by xy-git** [mapillary/mapillary_sls#28]
I have tried many times and tried different VPN, but I can't open the url  https://www.mapillary.com/dataset/places.
Where can I download the Mapillary Street-level Sequences dataset?
Can u help me? thanks a lot!

**Comment by xuzhuang1996** [comment]
> I have tried many times and tried different VPN, but I can't open the url https://www.mapillary.com/dataset/places. Where can I download the Mapillary Street-level Sequences dataset? Can u help me? thanks a lot!

check you VPN

I had download this dataset success

**Comment by mlopezantequera** [comment]
The dataset is hosted in Meta infrastructure which might be blocked in some countries -- Sorry for this inconvenience but we can't work around it
