### ISSUE TITLE
No csv files found in data downloaded

### ISSUE THREAD

**Issue by lr87** [mapillary/mapillary_sls#29]
Hi，I have download all the zip files from [https://www.mapillary.com/dataset/places](url).
After unziped, I found no csv files (there expect to be seq_info.csv, subtask_index.csv etc.)
![zip_file_show](https://user-images.githubusercontent.com/13805446/163095179-3e7a65bb-a06a-4b07-b641-f64588a2ef9a.png)

Please check if the zip files are good to use.

**Comment by mlopezantequera** [comment]
@lr87 , all the csv files are in the msls_metadata.zip file

![image](https://user-images.githubusercontent.com/1034087/163108794-dd7437e6-61ce-4017-8466-caf8777d1f1e.png)

**Comment by lr87** [comment]
@mlopezantequera  Thanks， I got it.
