### ISSUE TITLE
Challenge: BadZipfile

### ISSUE THREAD

**Issue by Tobias-Fischer** [mapillary/mapillary_sls#8]
Hiya, I get the following error when trying to submit to the challenge:

```
Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 132, in get_bundle
    with ZipFile(bundle_file.file, 'r') as z:
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

The zip file contains only the predictions.csv file. I can open the zipfile alright in a Python 2 environment on my local machine. I tried several ways to compress the zip file, too. I attach one of the zip files that didn't work.

It would be great if you could let me know how to get around this issue.

Best, Tobias
[predictions.zip](https://github.com/mapillary/mapillary_sls/files/5087899/predictions.zip)

**Comment by mlopezantequera** [comment]
Hi @Tobias-Fischer , thanks for the heads-up. We're looking into this, will let you know once it's fixed

**Comment by mlopezantequera** [comment]
@Tobias-Fischer , the issue is fixed now. Can you try again?

**Comment by Tobias-Fischer** [comment]
Yes that's working now, thanks @mlopezantequera
